name: cpc37v2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - psutil
  - pip
  - openblas-devel
  - tqdm
  - nose
  - cython
  - pysoundfile
  - pip:
    - progressbar2
    - matplotlib

#conda remove --force libsndfile